{{- if .Values.serviceAccount.create -}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rustrial-aws-eks-iam-auth-controller.serviceAccountName" . }}
  labels:
    {{- include "rustrial-aws-eks-iam-auth-controller.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "rustrial-aws-eks-iam-auth-controller.serviceAccountName" . }}
  labels:
    {{- include "rustrial-aws-eks-iam-auth-controller.labels" . | nindent 4 }}
rules:
- apiGroups: ["iamauthenticator.k8s.aws"]
  resources: ["iamidentitymappings", "iamidentitymappings/status"]
  verbs: ["list", "get", "watch", "create", "delete", "patch"]
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["aws-auth"]
  verbs: ["list", "get", "watch", "create", "delete", "patch"]
- apiGroups: [""]
  resources: ["endpoints", "services"]
  verbs: ["get", "list", "watch"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "rustrial-aws-eks-iam-auth-controller.serviceAccountName" . }}
  labels:
    {{- include "rustrial-aws-eks-iam-auth-controller.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "rustrial-aws-eks-iam-auth-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rustrial-aws-eks-iam-auth-controller.serviceAccountName" . }}
{{- end }}

